In [114]:
# Import Necessary Libraries
import numpy as np
import pandas as pd

In [115]:
# Load the dataset
dataset = pd.read_csv('IRIS.csv')

In [ ]:
# Data Preprocessing
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [116]:
# Encode Categorical Variables
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [117]:
# Split the dataset into training and testing data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [118]:
# Scale the features
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [119]:
# Support Vector Model
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 42)

In [ ]:
# Hyperparameter tuning using GridSearchCV
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.1,1, 10, 100], 'gamma': [1,0.1,0.01,0.001],'kernel': ['rbf']}
grid_search = GridSearchCV(SVC(),param_grid,refit=True,verbose=2)
#grid_search = GridSearchCV(estimator=classifier1, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train, y_train)

In [121]:
# Train the Support Vector Model
classifier.fit(X_train, y_train)

SVC(random_state=42)

In [126]:
# Evaluate the Support Vector model
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix : ", "\n",cm)
print("Accuracy is :",accuracy_score(y_test, y_pred))

Confusion Matrix :  
 [[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
Accuracy is : 0.9736842105263158


In [128]:
# Import Tensorflow and Keras
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [130]:
# Neural Network model
nn_model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)
])

nn_model.compile(optimizer='adam', loss='mean_squared_error')

In [139]:
# Train the model
nn_model.fit(X_train, y_train, epochs=10, batch_size=32, verbose=0)

In [140]:
# Make predictions on the test set
nn_predictions = np.argmax(nn_model.predict(X_test), axis=-1)

2/2 [==============================] - 0s 6ms/step


In [144]:
# Evaluate the Neural Network model
from sklearn.metrics import mean_squared_error
nn_mse = mean_squared_error(y_test, nn_predictions)
print(f"Neural Network Mean Squared Error: {nn_mse}")

Neural Network Mean Squared Error: 1.368421052631579
